name: Update Image to be deployed

on:
  registry_package:
    types: [published]

jobs:
  update-image-version:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Echo
        run: echo {{ github.event }}

