name: Create and publish a Docker image

on:
  push:
    tags: [ v* ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.image.outputs.name }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: output image name
        id: image
        run: echo "::set-output name=name::${{ steps.meta.outputs.tags }}"

  update-k8s:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0

      - name: Update Image Version
        uses: mikefarah/yq@master
        with:
          cmd: yq eval '.deployment.image = "${{ needs.build-and-push-image.outputs.image }}"' -i infrastructure/helm/test-chart/values.yaml

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update deploy image to ${{ needs.build-and-push-image.outputs.image }}